apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-management
  template:
    metadata:
      labels:
        app: leave-management
    spec:
      containers:
      - name: lms-container
        image: your-docker-username/lms-app:latest # Change to your image name
        ports:
        - containerPort: 8080
